### PR TITLE
Browsing view translation

### PR DESCRIPTION
**Pull request by guenthermi**
Internationalization for browsing view

### CODE REVIEW

**Comment by mkroetzsch** [comment]
@guenthermi Please let me know when this branch should be considered for merging again.

**Comment by mkroetzsch** [comment]
I just merged the refactoring branch that split the code into small files. I am afraid that this code now needs to be redistributed. Maybe the easiest approach is to re-edit the changes in the new code. On the positive side, the refactoring should prevent such problems in the future.

**Comment by arsylum** [comment]
@guenthermi sorry for the conflict situation. I can offer to resolve the merge conflicts since I currently have a good overview of the apps structure. You might want to familiarize yourself with it however.

**Comment by guenthermi** [comment]
No problem, I will care about the conflict by myself.

**Pull request merged**
